apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ezbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ezbs
    app.kubernetes.io/part-of: ci1t-43256-0027-app
  name: devfile-sample-ezbs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ezbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ezbs
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0027-tenant/ci1t-43256-0027-app/devfile-sample-ezbs@sha256:153d11ca505ce1c3f2ceeb8f26019df4c312d30805f242584806f619badb549f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
