apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ezbs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0027-tenant/ci1t-43256-0027-app/devfile-sample-ezbs@sha256:153d11ca505ce1c3f2ceeb8f26019df4c312d30805f242584806f619badb549f
        name: my-nodejs
        resources: {}
status: {}
